org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
hermesEnabled=true
newArchEnabled=false
MYAPP_UPLOAD_STORE_FILE=shago-finote-release-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=shago-finote-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=shagya22
MYAPP_UPLOAD_KEY_PASSWORD=shagya22